# coding: UTF-8

source 'https://rubygems.org'

ruby '1.9.3'

gem 'rails', '3.1.12'   # Si se cambia -> bundle update rails
gem 'mysql2'

gem 'haml-rails'
group :assets do
  gem 'sass-rails', " ~> 3.1.0"
end


group :development do
  gem 'puma'
  gem 'better_errors'
  gem 'binding_of_caller'
end
