source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', branch: '4-1-stable'   # Si se cambia -> bundle update rails
gem 'pg'

gem 'tematica', git: 'git@github.com:Soluciones/tematica.git', tag: '4.0.0'

gem 'hamlit-rails'
group :assets do
  gem 'sass-rails', " ~> 4.0.0"
end


group :development do
  gem 'puma'
  gem 'better_errors'
  gem 'binding_of_caller'
end
